version: '3.8'

networks:
  sf_network:
    driver: bridge

services:
  sf_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sf_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPWD1
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - sf_network
  sf_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@developer.sk
      PGADMIN_DEFAULT_PASSWORD: StrongPWD1
    ports:
      - "8080:80"
    depends_on:
      - sf_db
    networks:
      - sf_network
  sf_api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - sf_db
      - sf_cache
    networks:
      - sf_network
    ports:
      - "9000:9000"
    env_file:
      - ./api/.env
      - ./api/.env.testing
    volumes:
      - ./api:/var/www/
  sf_cache:
    image: redis:alpine
    environment:
      REDIS_HOST: sf_cache
      REDIS_PORT: 6379
    networks:
      - sf_network

