version: '3.8'

networks:
  sf_network:
    driver: bridge

services:
  sf_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sf_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPWD1
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - sf_network
  sf_api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - sf_db
      - sf_cache
    networks:
      - sf_network
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/

  sf_cache:
    image: redis:alpine
    environment:
      REDIS_HOST: sf_cache
      REDIS_PORT: 6379
    networks:
      - sf_network
