<?php

namespace tests\Feature\E2E;

use tests\Feature\E2E\Abstract\BaseE2ETest;

class RestaurantE2ETest extends BaseE2ETest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRetrieveRestaurants(): void
    {
        $response = $this->get(route('api.restaurant.index'));

        $this->assertSuccessfullApiJsonStructure($response, [
            '*' => [
                'id',
                'name',
                'description',
                'address',
                'phone',
                'email',
                'website',
                'created_at',
                'updated_at',
            ],
        ]);
    }
}
